spring:
  application:
    name: gateway

server:
  port: 8080
  
eureka:
  instance: 
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://172.21.0.3:8081/eureka/
    fetch-registry: true
    register-with-eureka: true

zuul:
  sensitive-headers:
  - Cookie

jwt:
  config:
    login-url: /auth/login
    type: signed
    
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000